version: '3.8'
services:
  freight-cargo:
    build: .
    ports:
      - "${PORT}:8080"
    environment:
      - app.jwt.secret=${APP_JWT_SECRET}
      - app.cors.allowed-origins=*
    restart: unless-stopped 